[package]
name = "igor-microphoned-lib"
version = "0.1.0"
edition = "2018"
homepage = "https://github.com/IgorAutomation/"

[dependencies]
deepspeech = "0.8.0"
cpal = "0.12.1"
structopt = "0.3"
thiserror = "1.0.21"
tracing = "0.1"

[build-dependencies]
